on:
  # trigger action from GitHub GUI (testing, no publish)
  workflow_dispatch:
  release:
    types:
      - published

name: Publish on PyPI

jobs:
  make_sdist:
    name: Make Python SDist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build SDist
        run: pipx run build --sdist

      - name: Upload SDist
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  upload:
    needs: [make_sdist]
    environment: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: Get dist files
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - name: Publish on PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
