name: test

on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - 'master'

jobs:
  test:
    name: pytest (${{ matrix.cfg.os }}, ${{ matrix.cfg.python-version }})
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - {os: ubuntu-latest,  python-version: "3.7"}
          - {os: ubuntu-latest,  python-version: "3.8"}
          - {os: ubuntu-latest,  python-version: "3.9"}
          - {os: macos-latest,   python-version: "3.8"}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          python-version: ${{ matrix.cfg.python-version }}
          channels: conda-forge,defaults
          channel-priority: true
          auto-activate-base: true
      - name: Conda info
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort
      - name: Install dependencies
        shell: bash -l {0}
        run: mamba install numpy s2geometry pybind11 xtensor xtensor-python cmake pytest
      - name: Build and install pys2index
        shell: bash -l {0}
        run: |
          python -m pip install --no-deps -e .
          python -OO -c "import pys2index"
        env:
          S2_DIR: "$CONDA_PREFIX"
      - name: Run tests
        shell: bash -l {0}
        run: pytest . --verbose --color=yes
