name: test

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'

jobs:
  test:
    name: pytest (${{ matrix.os }}, ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment-dev.yml
          cache-environment: true
          cache-downloads: false
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Build and install pys2index
        shell: bash -l {0}
        run: |
          python -m pip install . --no-build-isolation --no-deps -vv --config-settings=cmake.build-type=Debug
          python -OO -c "import pys2index"
      - name: Run tests
        shell: bash -l {0}
        run: pytest . --verbose --color=yes
