name: test

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'

jobs:
  test:
    name: pytest (${{ matrix.os }}, ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "3.8", "3.9"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults
          channel-priority: true
          auto-activate-base: true
      - name: Conda info
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort
      - name: Install dependencies
        shell: bash -l {0}
        run: mamba install numpy s2geometry pybind11 xtensor xtensor-python>=0.24 cmake pytest
      - name: Build and install pys2index
        shell: bash -l {0}
        run: |
          export S2_DIR=$CONDA_PREFIX
          python -m pip install --no-deps -e .
          python -OO -c "import pys2index"
      - name: Run tests
        shell: bash -l {0}
        run: pytest . --verbose --color=yes
